"""add_pkce_and_nonce_to_oauth_states

Revision ID: a78cdac147f7
Revises: 
Create Date: 2026-04-13 08:07:11.219230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a78cdac147f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_states', sa.Column('code_verifier', sa.String(length=128), nullable=True))
    op.add_column('oauth_states', sa.Column('nonce', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth_states', 'nonce')
    op.drop_column('oauth_states', 'code_verifier')
    # ### end Alembic commands ###
